apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: TXlQYXNzd29yZH4xMjM=
  POSTGRES_USER: YWRtaW4xMjM=
  POSTGRES_DB: bXlfZGI=
