apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-cluster-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: name
  namespace: test
