apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: akv
  labels:
    aadpodidbinding: akv-identity
spec:
  containers:
  - name: ubuntu
    image: docker.io/dlsfrdm/intern:latest
    env:
    - name: MY_SECRET
      value: azurekeyvault@azurekeyvault
